import "../styles/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Ryan's Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="from-neutral-100 to-neutral-200 bg-gradient-to-b">
        <Toaster />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
