import "../styles/globals.css";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ryan's Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props): React.JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} from-neutral-100 to-neutral-200 bg-gradient-to-b`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
